apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-stats
  labels:
    app: pop-stats
spec:
  selector:
    matchLabels:
      app: pop-stats
  replicas: 1
  securityContext:
    # runAsNonRoot: true
    allowPrivilegeEscalation: true
  template:
    metadata:
      labels:
        app: pop-stats
    spec:
      containers:
      - name: pop-stats
        image: pop-stats
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          # runAsNonRoot: true
          allowPrivilegeEscalation: true
        env:
          - name: SITE_NAME
            value: "Site Name"
          - name: DEV_EXT_IP
            value: "8.8.8.8"